# -*- coding: utf-8 -*-
"""
Dictionary of subbasins estatistical remove bias method for each month.


Dictionary format:
    dict_remove_bias = {'basin': ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'], ...}


Parameters description:

    jan: January
    feb: February
    mar: March
    apr: April
    may: May
    jun: June
    jul: July
    aug: August
    sep: Septembre
    oct: October
    nov: November
    dec: December

Each month must have one of the 3 strings below:

    eqm_des: Empirical Quantile Mapping Desagregated.
    gqm_des: Gama Quantile Mapping Desagregated.
    crude: Crude value delivered from GFS model.


Usage:
    Used in the removal of the bias of the preciptation data from the GFS model.


Last update: 2017-06-09 11:03

"""

dict_remove_bias = {

'amazonas_balbina':                                  ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des',   'crude',   'crude',   'crude',   'crude',   'crude', 'eqm_des', 'gqm_des'] ,
'amazonas_belo_monte':                               ['gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'eqm_des'] ,
'amazonas_cachoeira_caldeirao':                      ['eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'amazonas_coaracy_nunes':                            ['eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'amazonas_coaracy_nunes_inc':                        ['eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude',   'crude', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'amazonas_colider':                                  ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'amazonas_colider_inc':                              ['eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'amazonas_curua_una':                                ['gqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude',   'crude',   'crude', 'eqm_des'] ,
'amazonas_dardanelos':                               ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des',   'crude', 'eqm_des', 'eqm_des',   'crude',   'crude', 'eqm_des'] ,
'amazonas_ferreira_gomes':                           ['eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'amazonas_ferreira_gomes_inc':                       ['gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude',   'crude', 'eqm_des',   'crude', 'eqm_des'] ,
'amazonas_guapore':                                  ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'amazonas_jirau':                                    ['gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'amazonas_jirau_inc':                                ['gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'amazonas_rondon_ii':                                ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'amazonas_samuel':                                   ['gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'eqm_des'] ,
'amazonas_santo_antonio':                            ['gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'amazonas_santo_antonio_do_jari':                    [  'crude',   'crude', 'gqm_des', 'gqm_des', 'gqm_des',   'crude',   'crude',   'crude', 'gqm_des',   'crude', 'gqm_des',   'crude'] ,
'amazonas_santo_antonio_inc':                        ['eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des'] ,
'amazonas_sao_manuel':                               ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'amazonas_sao_manuel_inc':                           ['gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'amazonas_sinop':                                    ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'amazonas_teles_pires':                              ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'amazonas_teles_pires_inc':                          ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,

'atlantico_leste_irape':                             ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'atlantico_leste_itapebi':                           ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'atlantico_leste_itapebi_inc':                       ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des'] ,
'atlantico_leste_pedra_do_cavalo':                   ['gqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude',   'crude',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des',   'crude'] ,
'atlantico_leste_santa_clara':                       ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude',   'crude',   'crude', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des'] ,

'atlantico_sudeste_henry_borden':                    ['gqm_des', 'gqm_des',   'crude',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'atlantico_sudeste_lajes_fontes_nova_pereira_passos':['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'atlantico_sudeste_pedras':                          ['gqm_des', 'gqm_des',   'crude',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'atlantico_sudeste_rosal':                           ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,

'atlantico_sul_capivari_cachoeira':                  ['gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'atlantico_sul_salto_pilao':                         ['gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,

'doce_aimores':                                      ['eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'doce_aimores_inc':                                  ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'doce_baguari':                                      ['eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'doce_baguari_inc':                                  ['gqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude',   'crude', 'gqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'doce_cadonga':                                      ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'doce_guilman':                                      ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'doce_mascarenhas':                                  ['eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'doce_mascarenhas_inc':                              ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'doce_porto_estrela':                                ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'doce_porto_estrela_inc':                            ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'doce_sa_carvalho':                                  ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'doce_sa_carvalho_inc':                              ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'doce_salto_grande':                                 ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,

'grande_agua_vermelha':                              ['gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'grande_agua_vermelha_inc':                          ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'grande_as_oliveira':                                ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'grande_as_oliveira_inc':                            ['eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des',   'crude',   'crude', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'grande_caconde':                                    ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'grande_camargos':                                   ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'grande_euclides_da_cunha':                          ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'grande_euclides_da_cunha_inc':                      ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'grande_funil_grande':                               ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'grande_funil_grande_inc':                           ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'grande_furnas':                                     ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'grande_furnas_inc':                                 ['gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'grande_igarapava':                                  ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'grande_igarapava_inc':                              ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'grande_itutinga':                                   ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'grande_itutinga_inc':                               ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'grande_jaguara':                                    ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'grande_jaguara_inc':                                ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'grande_lc_barreto':                                 ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'grande_lc_barreto_inc':                             ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'grande_marimbondo':                                 ['gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'grande_marimbondo_inc':                             ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'grande_mascarenhas_de_moraes':                      ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'grande_mascarenhas_de_moraes_inc':                  ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'grande_porto_colombia':                             ['gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'grande_porto_colombia_inc':                         ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'grande_volta_grande':                               ['eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'grande_volta_grande_inc':                           ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,

'iguacu_baixo_iguacu':                               ['eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'iguacu_baixo_iguacu_inc':                           ['eqm_des',   'crude', 'eqm_des',   'crude', 'eqm_des',   'crude', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'iguacu_foz_do_areia':                               ['eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'iguacu_fundao':                                     ['eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'iguacu_fundao_inc':                                 ['eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'gqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'iguacu_gov_jose_richa':                             ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'iguacu_gov_jose_richa_inc':                         [  'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'iguacu_jordao':                                     ['eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'iguacu_jordao_inc':                                 ['eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'iguacu_salto_osorio':                               ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'iguacu_salto_osorio_inc':                           ['eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'gqm_des',   'crude', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'iguacu_salto_santiago':                             ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'iguacu_salto_santiago_inc':                         ['eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'iguacu_santa_clara':                                ['eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'iguacu_segredo':                                    ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'iguacu_segredo_inc':                                ['eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'gqm_des',   'crude'] ,

'jacui_14_de_julho':                                 ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'jacui_14_de_julho_inc':                             ['eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'jacui_castro_alves':                                ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'jacui_dona_francisca':                              ['gqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'jacui_dona_francisca_inc':                          [  'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude'] ,
'jacui_ernestina':                                   ['eqm_des',   'crude',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude', 'eqm_des',   'crude'] ,
'jacui_itauba':                                      ['gqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'jacui_itauba_inc':                                  ['gqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'jacui_jacui':                                       ['eqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'jacui_jacui_inc':                                   [  'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'jacui_monte_claro':                                 ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'jacui_monte_claro_inc':                             ['eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'jacui_passo_real':                                  ['eqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'jacui_passo_real_inc':                              ['eqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,

'paraguai_itiquira':                                 ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'gqm_des', 'gqm_des',   'crude', 'eqm_des'] ,
'paraguai_jauru':                                    ['eqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des'] ,
'paraguai_manso':                                    ['eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paraguai_ponte_de_pedra':                           ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,

'paraiba_do_sul_anta':                               ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'paraiba_do_sul_anta_inc':                           ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'paraiba_do_sul_funil':                              ['gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des'] ,
'paraiba_do_sul_funil_inc':                          ['gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'paraiba_do_sul_ilha_dos_pombos':                    ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'paraiba_do_sul_ilha_dos_pombos_inc':                ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'paraiba_do_sul_itaocara_i':                         ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'paraiba_do_sul_itaocara_i_inc':                     ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paraiba_do_sul_jaguari':                            ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paraiba_do_sul_paraibuna':                          ['eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'paraiba_do_sul_picada':                             ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'paraiba_do_sul_santa_branca':                       ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'paraiba_do_sul_santa_branca_inc':                   ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'paraiba_do_sul_santa_cecilia':                      ['gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des'] ,
'paraiba_do_sul_santa_cecilia_inc':                  ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paraiba_do_sul_santana':                            ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'paraiba_do_sul_santana_inc':                        ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'paraiba_do_sul_sobragi':                            ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des'] ,
'paraiba_do_sul_sobragi_inc':                        ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'paraiba_do_sul_tocos':                              ['gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,

'parana_ilha_solteira':                              ['gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'parana_ilha_solteira_equivalente':                  ['gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'parana_ilha_solteira_equivalente_inc':              ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'parana_ilha_solteira_inc':                          ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'parana_itaipu':                                     ['gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des',   'crude',   'crude',   'crude',   'crude', 'eqm_des'] ,
'parana_itaipu_inc':                                 ['gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des'] ,
'parana_jupia':                                      ['gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'parana_jupia_inc':                                  ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'parana_porto_primavera':                            ['gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'parana_porto_primavera_inc':                        ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des'] ,

'paranaiba_barra_dos_coqueiros':                     ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_barra_dos_coqueiros_inc':                 ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_batalha':                                 ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_cachoeira_dourada':                       ['eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude',   'crude',   'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_cachoeira_dourada_inc':                   ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_cacu':                                    ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_capim_branco_i':                          ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_capim_branco_i_inc':                      ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_capim_branco_ii':                         ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_capim_branco_ii_inc':                     ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_corumba_i':                               ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_corumba_i_inc':                           ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_corumba_iii':                             ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_corumba_iii_inc':                         ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_corumba_iv':                              ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_emborcacao':                              ['eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude', 'gqm_des',   'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_emborcacao_inc':                          ['eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude',   'crude', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_espora':                                  ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_foz_do_rio_claro':                        ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_foz_do_rio_claro_inc':                    ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_itumbiara':                               ['eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude', 'gqm_des',   'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_itumbiara_inc':                           ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_miranda':                                 ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_miranda_inc':                             ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_nova_ponte':                              ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_salto':                                   ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_salto_rio_verdinho':                      ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_salto_rio_verdinho_inc':                  ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranaiba_sao_simao':                               ['gqm_des', 'eqm_des', 'gqm_des', 'gqm_des',   'crude',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_sao_simao_inc':                           ['eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_serra_do_facao':                          ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'paranaiba_serra_do_facao_inc':                      ['eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,

'paranapanema_canoas_i':                             ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_canoas_i_inc':                         ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_canoas_ii':                            ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_canoas_ii_inc':                        ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des',   'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_capivara':                             ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_capivara_inc':                         ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_chavantes':                            ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_chavantes_inc':                        ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_jurumirim':                            ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranapanema_maua':                                 ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_ourinhos':                             ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_ourinhos_inc':                         ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_piraju':                               ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranapanema_piraju_inc':                           ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'paranapanema_rosana':                               ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_rosana_inc':                           ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'paranapanema_salto_grande_l_n_garcez':              ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_salto_grande_l_n_garcez_inc':          ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_taquarucu_escola_politecnica':         ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'paranapanema_taquarucu_escola_politecnica_inc':     ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,

'parnaiba_boa_esperanca':                            ['eqm_des', 'gqm_des', 'gqm_des', 'gqm_des',   'crude',   'crude',   'crude',   'crude', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,

'sao_francisco_apolonio_sales':                      ['gqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'sao_francisco_apolonio_sales_inc':                  ['eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des',   'crude',   'crude',   'crude',   'crude', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'sao_francisco_complexo_paulo_afonso':               ['gqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'sao_francisco_complexo_paulo_afonso_inc':           [  'crude',   'crude',   'crude',   'crude', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des',   'crude'] ,
'sao_francisco_itaparica':                           ['gqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'sao_francisco_itaparica_inc':                       ['gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude',   'crude',   'crude',   'crude', 'eqm_des',   'crude',   'crude'] ,
'sao_francisco_paulo_afonso':                        ['gqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'sao_francisco_paulo_afonso_inc':                    ['eqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des',   'crude',   'crude',   'crude',   'crude', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'sao_francisco_queimado':                            ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'sao_francisco_retiro_baixo':                        ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'sao_francisco_sobradinho':                          ['gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des'] ,
'sao_francisco_sobradinho_inc':                      ['gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'gqm_des'] ,
'sao_francisco_tres_marias':                         ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'sao_francisco_tres_marias_inc':                     ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'sao_francisco_xingo':                               ['gqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'sao_francisco_xingo_inc':                           [  'crude',   'crude',   'crude',   'crude', 'gqm_des', 'gqm_des',   'crude',   'crude',   'crude', 'gqm_des', 'eqm_des',   'crude'] ,

'tiete_bariri':                                      ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'tiete_bariri_inc':                                  ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'tiete_barra_bonita':                                ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'tiete_barra_bonita_inc':                            ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'tiete_billings':                                    ['gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'tiete_billings_mais_pedras':                        ['gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'tiete_edgard_de_souza':                             ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'tiete_edgard_de_souza_inc':                         ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'tiete_guarapiranga':                                ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'tiete_ibitinga':                                    ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'tiete_ibitinga_inc':                                ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'tiete_nova_avanhandava':                            ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'tiete_nova_avanhandava_inc':                        ['eqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude',   'crude', 'gqm_des',   'crude', 'eqm_des',   'crude', 'eqm_des', 'gqm_des'] ,
'tiete_ponte_nova':                                  ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des'] ,
'tiete_promissao':                                   ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'tiete_promissao_inc':                               ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'tiete_traicao':                                     ['gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'tiete_traicao_inc':                                 ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'tiete_tres_irmaos':                                 ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'tiete_tres_irmaos_inc':                             ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des',   'crude', 'eqm_des',   'crude',   'crude', 'eqm_des', 'gqm_des', 'gqm_des'] ,

'tocantins_cana_brava':                              ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'tocantins_cana_brava_inc':                          ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des',   'crude',   'crude',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des'] ,
'tocantins_estreito_tocantins':                      ['eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'tocantins_estreito_tocantins_inc':                  ['eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'tocantins_lajeado':                                 ['eqm_des', 'gqm_des', 'eqm_des', 'gqm_des',   'crude', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des'] ,
'tocantins_lajeado_inc':                             ['eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des'] ,
'tocantins_peixe_angical':                           ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des'] ,
'tocantins_peixe_angical_inc':                       ['eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des'] ,
'tocantins_sao_salvador':                            ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'tocantins_sao_salvador_inc':                        ['eqm_des', 'eqm_des', 'gqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des',   'crude',   'crude', 'gqm_des', 'gqm_des', 'eqm_des'] ,
'tocantins_serra_da_mesa':                           ['eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des'] ,
'tocantins_tucurui':                                 ['eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'tocantins_tucurui_inc':                             ['gqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'gqm_des',   'crude', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des'] ,

'uruguai_barra_grande':                              ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_campos_novos':                              ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_campos_novos_inc':                          ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_foz_do_chapeco':                            ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_foz_do_chapeco_inc':                        ['gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_garibaldi':                                 ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_garibaldi_inc':                             ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_ita':                                       ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_ita_inc':                                   ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'uruguai_machadinho':                                ['eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_machadinho_inc':                            ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_monjolinho':                                ['eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_monjolinho_inc':                            ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_passo_fundo':                               ['eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_passo_sao_joao':                            ['eqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_passo_sao_joao_inc':                        ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des',   'crude', 'eqm_des'] ,
'uruguai_quebra_queixo':                             ['eqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des'] ,
'uruguai_sao_jose':                                  ['eqm_des', 'eqm_des',   'crude', 'gqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des'] ,
'uruguai_sao_roque':                                 ['eqm_des', 'eqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'gqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des', 'eqm_des']
}
