# -*- coding: utf-8 -*-

# Author = 'Funceme'
# Credits = 'Diogenes Fontenele', 'Leidinice Silva'
# Maintainer = 'Funceme'
# Date = 29/01/2018  (dd/mm/aaaa)
# Comment = 'Este script foi desenvolvido dentro do Termo de Cooperação
#            0050.0100467.16.9 entre Funceme e Petrobras sob o contexto do
#            Projeto Projeção de Vazão Natural Afluente com base na escala de
#            tempo e clima'
# Description = 'Dictionary of subbasins estatistical remove bias method for
#                each month.'


"""
Dictionary of subbasins estatistical remove bias method for each month.


Dictionary format:
    dict_remove_bias = {'basin': ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'], ...}


Parameters description:

    jan: January
    feb: February
    mar: March
    apr: April
    may: May
    jun: June
    jul: July
    aug: August
    sep: Septembre
    oct: October
    nov: November
    dec: December

Each month must have one of the 4 strings below:

    cor_pr:      Value simulated with the precipitation corrected delivered of GFDL_CM2P5_FLOR_B01 model.
    cor_flow:    Value simulated with the flow corrected delivered of GFDL_CM2P5_FLOR_B01 model.
    cor_pr_flow: Value simulated with the flow corrected with the precipitation delivered of GFDL_CM2P5_FLOR_B01 model.
    crude:       Crude value delivered from GFDL_CM2P5_FLOR_B01 model.

Usage:
    Used in the removal of the bias of the flow data from the GFDL_CM2P5_FLOR_B01 model.


Last update: 2018-01-29 15:48

"""

dict_remove_bias={


'amazonas_balbina':										[                     'par',          'nmme_ncep-cfsv2',	              'echam46',         'nmme_cmc1-cancm3',	        'nmme_cmc2-cancm4',	        'nmme_cmc2-cancm4',	        'nmme_cmc2-cancm4',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	'nmme_nasa-gmao-062012', 	        'parx_parx-sst']
'amazonas_belo_monte'									[   'nmme_cola-rsmas-ccsm4',                  'echam46',	'nmme_cola-rsmas-ccsm4', 'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc2-cancm4',    	    'nmme_cmc2-cancm4',	        'nmme_cmc2-cancm4',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	              'echam46',	     'nmme_cmc1-cancm3',    'nmme_cola-rsmas-ccsm4']
'amazonas_belo_monte_complementar_art':					[   'nmme_cola-rsmas-ccsm4',                  'echam46',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	                 'echam46',	                 'echam46',	        'nmme_cmc2-cancm4',	'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	              'echam46',	              'echam46',    'nmme_cola-rsmas-ccsm4']
'amazonas_belo_monte_principal_art':				    [   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	        'nmme_cmc2-cancm4',	                     'par',	           'parx_parx-sst',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	'nmme_nasa-gmao-062012',	        'parx_parx-sst']
'amazonas_cachoeira_caldeirao':							[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	        'nmme_cmc2-cancm4',	        'nmme_cmc2-cancm4',	                     'par',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	'nmme_nasa-gmao-062012',  	        'parx_parx-sst']
'amazonas_coaracy_nunes':								[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	        'nmme_cmc2-cancm4',	        'nmme_cmc2-cancm4',	                     'par',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	'nmme_nasa-gmao-062012',	        'parx_parx-sst']
'amazonas_colider':										[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	        'nmme_cmc2-cancm4',         'nmme_cmc2-cancm4',	                     'par',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	        'parx_parx-sst']
'amazonas_curua_una':									[   'nmme_cola-rsmas-ccsm4',                  'echam46',				  'echam46',	              'echam46',	                 'echam46',	                     'par',	                     'par',	                 'echam46',	              'echam46',	                  'par',	'nmme_nasa-gmao-062012',    'nmme_cola-rsmas-ccsm4']
'amazonas_dardanelos':									[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	                  'par',	        'nmme_cmc2-cancm4',                   	 'par',	        'nmme_cmc2-cancm4',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	                  'par',	                  'par']
'amazonas_ferreira_gomes':								[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	        'nmme_cmc2-cancm4',	                     'par',	        'nmme_cmc2-cancm4',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	'nmme_nasa-gmao-062012',	        'parx_parx-sst']
'amazonas_guapore':								   	    [   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	                  'par',	        'nmme_cmc2-cancm4',	                     'par',	                     'par',	                     'par',	     'nmme_cmc1-cancm3',	                  'par',	'nmme_nasa-gmao-062012',    'nmme_cola-rsmas-ccsm4']
'amazonas_jirau':									    [   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	                  'par',	        'nmme_cmc2-cancm4',	                     'par',	        'nmme_cmc2-cancm4',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	'nmme_nasa-gmao-062012',	                  'par']
'amazonas_rondon_ii':									[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	    			  'par',	        'nmme_cmc2-cancm4',	                     'par',	                     'par',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	'nmme_nasa-gmao-062012',    'nmme_cola-rsmas-ccsm4']
'amazonas_samuel':										[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	        'nmme_cmc2-cancm4',	        'nmme_cmc2-cancm4',	        'nmme_cmc2-cancm4',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	              'echam46',	        'parx_parx-sst']
'amazonas_santo_antonio':								[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	                  'par',	                 'echam46',	                     'par',	                     'par',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	'nmme_nasa-gmao-062012',    'nmme_cola-rsmas-ccsm4']
'amazonas_santo_antonio_do_jari':						[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	              'echam46',	                 'echam46',	                     'par',	                     'par',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	'nmme_nasa-gmao-062012',    'nmme_cola-rsmas-ccsm4']
'amazonas_sao_manuel':									[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	        'nmme_cmc2-cancm4',	                     'par',	        'nmme_cmc2-cancm4',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	        'parx_parx-sst']
'amazonas_sinop':										[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	        'nmme_cmc2-cancm4',	        'nmme_cmc2-cancm4',	        'nmme_cmc2-cancm4',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	                  'par',	     'nmme_cmc1-cancm3',	        'parx_parx-sst']
'amazonas_teles_pires':									[   'nmme_cola-rsmas-ccsm4',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',  	        'nmme_cmc2-cancm4',	                     'par',	        'nmme_cmc2-cancm4',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',    	    'parx_parx-sst']
'atlantico_leste_irape':								[         'nmme_ncep-cfsv2',          'parx_parx-echam', 'nmme_gfdl-cm2p5-flor-b01',	                  'par',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc1-cancm3',	                     'par',	        'parx_parx-sst',	'nmme_cola-rsmas-ccsm4',	'nmme_cola-rsmas-ccsm3',    'nmme_cola-rsmas-ccsm3']
'atlantico_leste_itapebi':								[         'nmme_ncep-cfsv2',          'parx_parx-echam', 'nmme_gfdl-cm2p5-flor-b01',	        'parx_parx-sst',	   'nmme_cola-rsmas-ccsm3',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc1-cancm3',	           'parx_parx-sst',	        'parx_parx-sst',	'nmme_cola-rsmas-ccsm4',	'nmme_cola-rsmas-ccsm3',    'nmme_cola-rsmas-ccsm3']
'atlantico_leste_pedra_do_cavalo':						[         'nmme_ncep-cfsv2',          'parx_parx-echam', 'nmme_gfdl-cm2p5-flor-b01',	        'parx_parx-sst',	   'nmme_cola-rsmas-ccsm3',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc1-cancm3',	           'parx_parx-sst',	        'parx_parx-sst',	'nmme_cola-rsmas-ccsm4',	'nmme_cola-rsmas-ccsm3',    'nmme_cola-rsmas-ccsm3']
'atlantico_leste_santa_clara':							[         'nmme_ncep-cfsv2',          'parx_parx-echam', 'nmme_gfdl-cm2p5-flor-b01',	                  'par',	                     'par',	                     'par',	                 'echam46',	                     'par',	        'parx_parx-sst',	'nmme_cola-rsmas-ccsm4',	'nmme_cola-rsmas-ccsm3',	              'echam46']
'atlantico_sudeste_henry_borden_art':					['nmme_gfdl-cm2p5-flor-b01',          'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',	      'parx_parx-echam',	'nmme_cola-rsmas-ccsm3',	                  'par',	     'nmme_cmc1-cancm3']
'atlantico_sudeste_lajes_fontes_nova_pereira_passos':	['nmme_gfdl-cm2p5-flor-b01',          'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',    'nmme_cola-rsmas-ccsm3',	                  'par',	                  'par',	                  'par',	     'nmme_cmc1-cancm3']
'atlantico_sudeste_pedras':								[                 'echam46',          'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',	              'echam46',	'nmme_cola-rsmas-ccsm3',	                  'par',	     'nmme_cmc2-cancm4']
'atlantico_sudeste_rosal':								[                 'echam46',          'nmme_ncep-cfsv2',      	          'echam46',	     'nmme_cmc1-cancm3',	                 'echam46',	                 'echam46',	                 'echam46',	                     'par',	                  'par',	              'echam46',	      'nmme_ncep-cfsv2',	     'nmme_cmc2-cancm4']
'atlantico_sul_capivari_cachoeira':						[                 'echam46',                  'echam46',	                  'par',	      'nmme_ncep-cfsv2',	                 'echam46',	   'nmme_cola-rsmas-ccsm4',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	'nmme_cola-rsmas-ccsm3',	        'parx_parx-sst',    'nmme_cola-rsmas-ccsm4']
'atlantico_sul_salto_pilao':							[         'nmme_ncep-cfsv2',         'nmme_cmc2-cancm4',	              'echam46',	      'nmme_ncep-cfsv2',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm3',	        'parx_parx-sst',    'nmme_cola-rsmas-ccsm4']
'doce_aimores':											[   'nmme_nasa-gmao-062012',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	           'parx_parx-sst',	                 'echam46',	                     'par', 'nmme_nasa-gmao-062012',	              'echam46',	              'echam46',	     'nmme_cmc2-cancm4']
'doce_baguari':											[   'nmme_nasa-gmao-062012',      'parx_parx-echam-sst',	              'echam46',	              'echam46',	                 'echam46',	           'parx_parx-sst',	                 'echam46',	                     'par',	'nmme_nasa-gmao-062012',	              'echam46',	              'echam46',	     'nmme_cmc2-cancm4']
'doce_cadonga':											[   'nmme_nasa-gmao-062012',      'parx_parx-echam-sst',	              'echam46',	              'echam46',	                 'echam46',                      'par',	                 'echam46',	                 'echam46',	'nmme_nasa-gmao-062012',	              'echam46',	              'echam46',	     'nmme_cmc2-cancm4']
'doce_guilman':											[   'nmme_nasa-gmao-062012',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm3',	                  'par',	                     'par',	                     'par',	                 'echam46',	                 'echam46',	'nmme_nasa-gmao-062012',	              'echam46',	              'echam46',    'nmme_cola-rsmas-ccsm4']
'doce_mascarenhas':										[   'nmme_nasa-gmao-062012',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm3',	              'echam46',	   'nmme_cola-rsmas-ccsm3',	           'parx_parx-sst',	                 'echam46',	                     'par',	'nmme_nasa-gmao-062012',	              'echam46',	              'echam46',    'nmme_cola-rsmas-ccsm4']
'doce_porto_estrela':									[   'nmme_nasa-gmao-062012',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	           'parx_parx-sst',	                 'echam46',	                     'par',	'nmme_nasa-gmao-062012',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',    'nmme_cola-rsmas-ccsm4']
'doce_sa_carvalho':										[   'nmme_nasa-gmao-062012',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4',	                     'par',	                     'par',	                 'echam46',	                 'echam46',	'nmme_nasa-gmao-062012',	              'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm4']
'doce_salto_grande':									[   'nmme_nasa-gmao-062012',          'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',            'parx_parx-sst',	                 'echam46',	                     'par',	'nmme_nasa-gmao-062012',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4']
'grande_agua_vermelha':									[         'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	      'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	                 'echam46',	                 'echam46',	              'echam46',	              'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'grande_as_oliveira':									[         'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	      'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	                 'echam46',	                 'echam46',	              'echam46',	              'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'grande_caconde':										[         'nmme_ncep-cfsv2',          'nmme_ncep-cfsv2',	      'nmme_ncep-cfsv2',     	 'nmme_cmc2-cancm4',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',                	 'echam46',	                 'echam46',	              'echam46',	              'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'grande_camargos':										[         'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',	                 'echam46',	                 'echam46',	                  'par',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3']
'grande_euclides_da_cunha':								[                 'echam46', 'nmme_gfdl-cm2p5-flor-b01',	      'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',	                 'echam46',	                 'echam46',	              'echam46',	        'parx_parx-sst',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'grande_funil_grande':									[         'nmme_ncep-cfsv2',                  'echam46',	      'nmme_ncep-cfsv2',  	              'echam46',	'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	                 'echam46',	                 'echam46',	              'echam46',	                  'par', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3']
'grande_furnas':										[         'nmme_ncep-cfsv2',                  'echam46',	      'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',	                 'echam46',	                 'echam46',	              'echam46',	        'parx_parx-sst',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'grande_igarapava':										[         'nmme_ncep-cfsv2',                  'echam46',	              'echam46',	              'echam46',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',	                 'echam46',	                 'echam46',	              'echam46',	        'parx_parx-sst',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'grande_itutinga':										[         'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	      'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',                  'echam46',            'parx_parx-sst',	                  'par',	                  'par', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3']
'grande_jaguara':										[         'nmme_ncep-cfsv2',                  'echam46',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',	                 'echam46',	                 'echam46',	              'echam46',	        'parx_parx-sst',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'grande_lc_barreto':									[         'nmme_ncep-cfsv2',                  'echam46',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',	                 'echam46',	                 'echam46',	              'echam46',	        'parx_parx-sst',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'grande_marimbondo':									[         'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	      'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	                 'echam46',	                 'echam46',	                 'echam46',	              'echam46',	              'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'grande_mascarenhas_de_moraes':							[         'nmme_ncep-cfsv2',                  'echam46',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',	                 'echam46',	                 'echam46',	              'echam46',	        'parx_parx-sst',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'grande_porto_colombia':								[         'nmme_ncep-cfsv2', 'nmme_gfdl-cm2p5-flor-b01',	      'nmme_ncep-cfsv2',	              'echam46',	'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	                 'echam46',	                 'echam46',               'echam46',	              'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'grande_volta_grande':									[         'nmme_ncep-cfsv2',                  'echam46',	      'nmme_ncep-cfsv2',	              'echam46',	'nmme_gfdl-cm2p5-flor-b01',	   'nmme_cola-rsmas-ccsm3',	                 'echam46',	                 'echam46',	              'echam46',	        'parx_parx-sst',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'iguacu_baixo_iguacu':									[        'nmme_cmc1-cancm3',                  'echam46',	              'echam46',	'nmme_nasa-gmao-062012',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',               'echam46',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01']
'iguacu_foz_do_areia':									[                 'echam46',                  'echam46',	              'echam46',	'nmme_nasa-gmao-062011',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	'nmme_cola-rsmas-ccsm4',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01']
'iguacu_fundao':										[        'nmme_cmc1-cancm3',            'parx_parx-sst',	              'echam46',	'nmme_nasa-gmao-062010',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	              'echam46',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01']
'iguacu_gov_jose_richa':								[        'nmme_cmc1-cancm3',                  'echam46',	              'echam46',	'nmme_nasa-gmao-062009',	         'nmme_ncep-cfsv2',	                 'echam46',    'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	              'echam46',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01']
'iguacu_jordao':										[        'nmme_cmc1-cancm3',            'parx_parx-sst',	              'echam46',	'nmme_nasa-gmao-062008',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	'nmme_cola-rsmas-ccsm4',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01']
'iguacu_jordao_art':									[        'nmme_cmc1-cancm3',         'nmme_cmc1-cancm3',	     'nmme_cmc2-cancm4',	'nmme_nasa-gmao-062007',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	'nmme_cola-rsmas-ccsm4',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01']
'iguacu_salto_osorio':									[        'nmme_cmc1-cancm3',                  'echam46',				  'echam46',	'nmme_nasa-gmao-062006',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	              'echam46',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01']
'iguacu_salto_santiago':								[        'nmme_cmc1-cancm3',                  'echam46',			   	  'echam46',	'nmme_nasa-gmao-062005',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	              'echam46',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01']
'iguacu_santa_clara':									[        'nmme_cmc1-cancm3',            'parx_parx-sst',				  'echam46',	'nmme_nasa-gmao-062004',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	              'echam46',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01']
'iguacu_segredo':										[        'nmme_cmc1-cancm3',                  'echam46',				  'echam46',	'nmme_nasa-gmao-062003',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	'nmme_cola-rsmas-ccsm4',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01']
'iguacu_segredo_mais_desvio_art':						[        'nmme_cmc1-cancm3',                  'echam46',				  'echam46',	              'echam46',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	   'nmme_nasa-gmao-062012',	              'echam46',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01']
'jacui_14_de_julho':									['nmme_gfdl-cm2p5-flor-b01',         'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_nasa-gmao-062012',	        'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	         'nmme_ncep-cfsv2',	      'parx_parx-echam',	'nmme_cola-rsmas-ccsm4',	      'nmme_ncep-cfsv2',    'nmme_cola-rsmas-ccsm4']
'jacui_castro_alves':									['nmme_gfdl-cm2p5-flor-b01',         'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01',    'nmme_nasa-gmao-062012',	        'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	         'nmme_ncep-cfsv2',	      'parx_parx-echam',	'nmme_cola-rsmas-ccsm4',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4']
'jacui_dona_francisca':									['nmme_gfdl-cm2p5-flor-b01',                  'echam46', 'nmme_gfdl-cm2p5-flor-b01',    'nmme_nasa-gmao-062012',	        'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	                 'echam46',   	  'parx_parx-echam',	'nmme_cola-rsmas-ccsm4',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4']
'jacui_ernestina':										['nmme_gfdl-cm2p5-flor-b01',         'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_nasa-gmao-062012',	        'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	                 'echam46',	      'parx_parx-echam',	'nmme_cola-rsmas-ccsm4',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4']
'jacui_itauba':											['nmme_gfdl-cm2p5-flor-b01',                  'echam46',	              'echam46',	'nmme_nasa-gmao-062012',	        'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	                 'echam46',	      'parx_parx-echam',	'nmme_cola-rsmas-ccsm4',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4']
'jacui_jacui':											['nmme_gfdl-cm2p5-flor-b01',                  'echam46',	              'echam46',	'nmme_nasa-gmao-062012',	        'nmme_cmc1-cancm3',  	     'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	                 'echam46',		  'parx_parx-echam',	'nmme_cola-rsmas-ccsm4',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4']
'jacui_monte_claro':									['nmme_gfdl-cm2p5-flor-b01',         'nmme_cmc2-cancm4',	'nmme_cola-rsmas-ccsm4',	'nmme_nasa-gmao-062012',	        'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	         'nmme_ncep-cfsv2',		  'parx_parx-echam',	'nmme_cola-rsmas-ccsm4',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4']
'jacui_passo_real':										['nmme_gfdl-cm2p5-flor-b01',                  'echam46',	              'echam46',	'nmme_nasa-gmao-062012',	        'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	   'nmme_nasa-gmao-062012',	                 'echam46',	  	  'parx_parx-echam',	'nmme_cola-rsmas-ccsm4',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm4']
'paraguai_itiquira':	           				 		[        'nmme_cmc1-cancm3',    'nmme_cola-rsmas-ccsm3',	        'parx_parx-sst',	                  'par',	           'parx_parx-sst',	                 'echam46',	                     'par',	                     'par',	        'parx_parx-sst',	        'parx_parx-sst',	     'nmme_cmc1-cancm3',	              'echam46']
'paraguai_itiquira_ii':							 		[        'nmme_cmc1-cancm3',    'nmme_cola-rsmas-ccsm3',	        'parx_parx-sst',	                  'par',	           'parx_parx-sst',	                 'echam46',	                     'par',	                     'par',	        'parx_parx-sst',	        'parx_parx-sst',	              'echam46',	              'echam46']
'paraguai_jauru':								 		[        'nmme_cmc1-cancm3',    'nmme_cola-rsmas-ccsm3',	        'parx_parx-sst',	        'parx_parx-sst',	           'parx_parx-sst',	   'nmme_cola-rsmas-ccsm3',	           'parx_parx-sst',	   'nmme_nasa-gmao-062012',	        'parx_parx-sst',	'nmme_cola-rsmas-ccsm3',	'nmme_nasa-gmao-062012',	        'parx_parx-sst']
'paraguai_manso':								 		[        'nmme_cmc1-cancm3',    'nmme_cola-rsmas-ccsm3',	              'echam46',	              'echam46',	           'parx_parx-sst',	   'nmme_cola-rsmas-ccsm3',	           'parx_parx-sst',	   'nmme_nasa-gmao-062012',	        'parx_parx-sst',	        'parx_parx-sst',	              'echam46',	        'parx_parx-sst']
'paraguai_ponte_de_pedra':								[        'nmme_cmc1-cancm3',    'nmme_cola-rsmas-ccsm3',	        'parx_parx-sst',	                  'par',	           'parx_parx-sst',	                     'par',	                     'par',	   'nmme_nasa-gmao-062012',	        'parx_parx-sst',	'nmme_cola-rsmas-ccsm3',	'nmme_nasa-gmao-062012',	        'parx_parx-sst']
'paraiba_do_sul_anta':									[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	                     'par',	                 'echam46',	              'echam46',	              'echam46',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_anta_art':								[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	                     'par',	                 'echam46',	     'nmme_cmc2-cancm4',	              'echam46',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_fontes_art':							[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_funil':									[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	                 'echam46',	     'nmme_cmc2-cancm4',	'nmme_cola-rsmas-ccsm3',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_ilha_dos_pombos':						[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	                 'echam46',	              'echam46',	              'echam46',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_ilha_dos_pombos_art':					[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	              'echam46',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_itaocara_i':							[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	                 'echam46',	              'echam46',	              'echam46',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_itaocara_i_art':						[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	              'echam46',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_jaguari':								[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc2-cancm4',	'nmme_cola-rsmas-ccsm3',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_lajes_art':								[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	           'parx_parx-sst',	           'parx_parx-sst',	     'nmme_cmc2-cancm4',	              'echam46',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_nilo_pecanha_art':						[                 'echam46', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	                  'par',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	           'parx_parx-sst',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc2-cancm4',	                  'par',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_paraibuna':								[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	           'parx_parx-sst',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc2-cancm4',	'nmme_cola-rsmas-ccsm3',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_pereira_passos_art':					[                     'par', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	                  'par',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	           'parx_parx-sst',	           'parx_parx-sst', 	 'nmme_cmc2-cancm4',	                  'par',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_picada':								[                 'echam46',                  'echam46',    'nmme_cola-rsmas-ccsm4',	              'echam46',	                 'echam46',	                 'echam46',	                 'echam46',	                     'par',	     'nmme_cmc2-cancm4',	                  'par',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_santa_branca':							[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	           'parx_parx-sst',	'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	'nmme_cola-rsmas-ccsm3',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_santa_cecilia':	               			[                     'par', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	           'parx_parx-sst',	                 'echam46',	     'nmme_cmc2-cancm4',	'nmme_cola-rsmas-ccsm3',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_santa_cecilia_bombeamento_art':			[                 'echam46', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	           'parx_parx-sst',	'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc2-cancm4',	                  'par',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_santana':								[                 'echam46', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	                 'echam46',	           'parx_parx-sst',	           'parx_parx-sst',	              'echam46',	              'echam46',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_santana_art':							[                 'echam46', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	                  'par',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',    	       'parx_parx-sst',	'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	'nmme_cola-rsmas-ccsm3',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_santana_vertimento_art':				[                 'echam46', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                 'echam46',	                 'echam46',	                 'echam46',	                 'echam46',	              'echam46',	              'echam46',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_simplicio_art':							[                     'par', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	           'parx_parx-sst',	           'parx_parx-sst',	     'nmme_cmc2-cancm4',	              'echam46',	              'echam46',	              'echam46']
'paraiba_do_sul_sobragi':								[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01',    'nmme_cola-rsmas-ccsm4',	              'echam46',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	           'parx_parx-sst',	     'nmme_cmc2-cancm4',	              'echam46',	              'echam46',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_tocos':									[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01',    'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3',	                 'echam46',	'nmme_gfdl-cm2p5-flor-b01',	                     'par',	           'parx_parx-sst',	     'nmme_cmc2-cancm4',	              'echam46',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_tocos_vertimento_art':					[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4', 	              'echam46',	                 'echam46',	                 'echam46',	                 'echam46',	           'parx_parx-sst',	     'nmme_cmc2-cancm4',	              'echam46',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3']
'paraiba_do_sul_vigario_art'							[                 'echam46', 'nmme_gfdl-cm2p5-flor-b01', 'nmme_gfdl-cm2p5-flor-b01',	                  'par',	         'nmme_ncep-cfsv2',	'nmme_gfdl-cm2p5-flor-b01',	           'parx_parx-sst',	'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	'nmme_cola-rsmas-ccsm3',	              'echam46',	     'nmme_cmc1-cancm3']
'parana_ilha_solteira':									[        'nmme_cmc1-cancm3',          'nmme_ncep-cfsv2',	     'nmme_cmc1-cancm3',	              'echam46',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc2-cancm4',	   'nmme_nasa-gmao-062012',	                 'echam46',	     'nmme_cmc2-cancm4',	'nmme_nasa-gmao-062012',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'parana_ilha_solteira_equivalente':						[        'nmme_cmc1-cancm3', 		  'nmme_ncep-cfsv2',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc2-cancm4',	   'nmme_nasa-gmao-062012',                	 'echam46',	     'nmme_cmc2-cancm4',	'nmme_nasa-gmao-062012',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'parana_ilha_solteira_equivalente_art':					[        'nmme_cmc1-cancm3', 		  'nmme_ncep-cfsv2',	     'nmme_cmc1-cancm3',	              'echam46',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc2-cancm4',	   'nmme_nasa-gmao-062012',	                 'echam46',	     'nmme_cmc2-cancm4',	'nmme_nasa-gmao-062012',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'parana_itaipu':										[                 'echam46',          'nmme_ncep-cfsv2',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc2-cancm4',	   'nmme_nasa-gmao-062012',	                 'echam46',	     'nmme_cmc2-cancm4',	              'echam46',	              'echam46',	'nmme_nasa-gmao-062012']
'parana_itaipu_art':									[                 'echam46',          'nmme_ncep-cfsv2',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc2-cancm4',	   'nmme_nasa-gmao-062012', 	             'echam46',	     'nmme_cmc2-cancm4',	              'echam46',	              'echam46',	'nmme_nasa-gmao-062012']
'parana_jupia':											[        'nmme_cmc1-cancm3',          'nmme_ncep-cfsv2',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc2-cancm4',	   'nmme_nasa-gmao-062012',	                 'echam46',	     'nmme_cmc2-cancm4',	'nmme_nasa-gmao-062012',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'parana_jupia_art':										[        'nmme_cmc1-cancm3',          'nmme_ncep-cfsv2',	     'nmme_cmc1-cancm3',	              'echam46',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc2-cancm4',	   'nmme_nasa-gmao-062012',	                 'echam46',	     'nmme_cmc2-cancm4',	'nmme_nasa-gmao-062012',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'parana_porto_primavera':								[        'nmme_cmc1-cancm3',          'nmme_ncep-cfsv2',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc2-cancm4',    'nmme_nasa-gmao-062012',	                 'echam46',	     'nmme_cmc2-cancm4',	'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm3']
'parana_porto_primavera_art':							[        'nmme_cmc1-cancm3',          'nmme_ncep-cfsv2',		 'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3',	'nmme_gfdl-cm2p5-flor-b01',	        'nmme_cmc2-cancm4',	   'nmme_nasa-gmao-062012',	        'nmme_cmc2-cancm4',	     'nmme_cmc2-cancm4',	'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm3']
'paranaiba_barra_dos_coqueiros':						[                 'echam46',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                     'par',	                     'par',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3']
'paranaiba_batalha':									[        'nmme_cmc2-cancm4',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                     'par',	         'nmme_ncep-cfsv2',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3']
'paranaiba_cachoeira_dourada':							[                 'echam46',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	              'echam46',       'nmme_cola-rsmas-ccsm3',	                 'echam46',	                 'echam46',	                 'echam46',	        'parx_parx-sst',                  'echam46',	              'echam46',	        'parx_parx-sst']
'paranaiba_cacu':										[        'nmme_cmc2-cancm4',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                     'par',	                     'par',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3']
'paranaiba_capim_branco_i':								[        'nmme_cmc1-cancm3',      'parx_parx-echam-sst',	     'nmme_cmc1-cancm3',	              'echam46',	   'nmme_cola-rsmas-ccsm3',	                     'par',	                 'echam46',	                 'echam46',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                  'par']
'paranaiba_capim_branco_ii':							[        'nmme_cmc1-cancm3',      'parx_parx-echam-sst',	     'nmme_cmc1-cancm3',	              'echam46',	   'nmme_cola-rsmas-ccsm3',	                     'par',	                 'echam46',	                 'echam46',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                  'par']
'paranaiba_corumba_i':									[        'nmme_cmc2-cancm4',      'parx_parx-echam-sst',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                  'cham46',	                 'echam46',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3']
'paranaiba_corumba_iii':								[        'nmme_cmc2-cancm4',                  'echam46',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	                     'par',                  'echam46',	         'nmme_ncep-cfsv2',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	     'nmme_cmc1-cancm3']
'paranaiba_corumba_iv':								    [        'nmme_cmc2-cancm4',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',  	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	        'nmme_cmc2-cancm4',	         'nmme_ncep-cfsv2',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3']
'paranaiba_emborcacao':									[        'nmme_cmc2-cancm4',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	                     'par',	                     'par',	                     'par',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	     'nmme_cmc1-cancm3']
'paranaiba_espora':										[        'nmme_cmc2-cancm4',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	        'nmme_cmc2-cancm4',	                     'par',	                  'par', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3']
'paranaiba_foz_do_rio_claro':							[        'nmme_cmc2-cancm4',         'nmme_cmc2-cancm4',  	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                     'par',	                     'par',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3']
'paranaiba_itumbiara':									[        'nmme_cmc2-cancm4',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	              'echam46',	   'nmme_cola-rsmas-ccsm3',	                 'echam46',	                 'echam46',	                 'echam46',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                  'par']
'paranaiba_miranda'										[        'nmme_cmc2-cancm4',      'parx_parx-echam-sst',	     'nmme_cmc1-cancm3',	              'echam46', 	   'nmme_cola-rsmas-ccsm3',	                     'par',	                 'echam46',	                 'echam46',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                  'par']
'paranaiba_nova_ponte':									[        'nmme_cmc2-cancm4',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	              'echam46',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	        'nmme_cmc2-cancm4',	                 'echam46',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                  'par']
'paranaiba_salto':										[        'nmme_cmc2-cancm4',                  'echam46',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc2-cancm4',	                     'par',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3']
'paranaiba_salto_rio_verdinho':							[        'nmme_cmc2-cancm4',                  'echam46',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc2-cancm4',	                     'par',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3']
'paranaiba_sao_simao':									[                 'echam46',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	              'echam46',	   'nmme_cola-rsmas-ccsm3',	                     'par',	                     'par',	         'nmme_ncep-cfsv2',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	                  'par']
'paranaiba_serra_do_facao':								[        'nmme_cmc2-cancm4',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	                     'par',	                     'par',	                 'echam46',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	     'nmme_cmc1-cancm3']
'paranapanema_canoas_i':							 	[   'nmme_cola-rsmas-ccsm3',          'nmme_ncep-cfsv2',	              'echam46',	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                 'echam46',	   'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3',                  'echam46',	     'nmme_cmc1-cancm3',	                  'par']
'paranapanema_canoas_ii':								[   'nmme_cola-rsmas-ccsm3',          'nmme_ncep-cfsv2',	              'echam46',  	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                 'echam46',	   'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3',                  'echam46',	     'nmme_cmc1-cancm3',	                  'par']
'paranapanema_capivara':						    	[	              'echam46',          'nmme_ncep-cfsv2',	              'echam46',	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	   'nmme_cola-rsmas-ccsm4',    'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3',    'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	              'echam46']
'paranapanema_chavantes':								[   'nmme_cola-rsmas-ccsm3',          'nmme_ncep-cfsv2',	              'echam46',  	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                 'echam46',	   'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3',    'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	                  'par']
'paranapanema_jurumirim':								[   'nmme_cola-rsmas-ccsm3',                  'echam46',				  'echam46',	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                 'echam46',	   'nmme_cola-rsmas-ccsm3',	              'echam46',    'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	                  'par']
'paranapanema_maua':									[   'nmme_cola-rsmas-ccsm3',          'nmme_ncep-cfsv2',				  'echam46',	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	   'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3',	'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	              'echam46']
'paranapanema_ourinhos':								[   'nmme_cola-rsmas-ccsm3',          'nmme_ncep-cfsv2',				  'echam46',	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                 'echam46',	   'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3',	'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	                  'par']
'paranapanema_piraju':									[   'nmme_cola-rsmas-ccsm3',                  'echam46',				  'echam46',	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                 'echam46',	   'nmme_cola-rsmas-ccsm3',	              'echam46',	'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	                  'par']
'paranapanema_rosana':									[                 'echam46',          'nmme_ncep-cfsv2',				  'echam46',	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	   'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	              'echam46',	'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	              'echam46']
'paranapanema_salto_grande_l_n_garcez':					[   'nmme_cola-rsmas-ccsm3',          'nmme_ncep-cfsv2',				  'echam46',	     'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                 'echam46',	   'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3',	              'echam46',	     'nmme_cmc1-cancm3',	                  'par']
'paranapanema_taquarucu_escola_politecnica':			[                 'echam46',          'nmme_ncep-cfsv2',				  'echam46',		 'nmme_cmc2-cancm4',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	   'nmme_cola-rsmas-ccsm4',	   'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3',	'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	              'echam46']
'parnaiba_boa_esperanca':								[   'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01',				  'echam46',                  'echam46',  	        'nmme_cmc2-cancm4',	                     'par',	                     'par',	   'nmme_nasa-gmao-062012',	'nmme_nasa-gmao-062012',	     'nmme_cmc2-cancm4',	      'nmme_ncep-cfsv2',	'nmme_nasa-gmao-062012']
'sao_francisco_apolonio_sales':							[        'nmme_cmc2-cancm4',         'nmme_cmc1-cancm3',		 'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01',	         'nmme_ncep-cfsv2',	                     'par',	           'parx_parx-sst',	           'parx_parx-sst',	'nmme_nasa-gmao-062012', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3']
'sao_francisco_complexo_paulo_afonso':					[        'nmme_cmc2-cancm4',         'nmme_cmc1-cancm3',		 'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01',	         'nmme_ncep-cfsv2',	                     'par',	           'parx_parx-sst',	           'parx_parx-sst',	'nmme_nasa-gmao-062012', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3']
'sao_francisco_itaparica':								[        'nmme_cmc2-cancm4',         'nmme_cmc1-cancm3',		 'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01',	         'nmme_ncep-cfsv2',	        'nmme_cmc1-cancm3',	                     'par',	           'parx_parx-sst',	'nmme_nasa-gmao-062012', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3']
'sao_francisco_itaparica_inc':							[        'nmme_cmc2-cancm4',    'nmme_cola-rsmas-ccsm4',		 'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01',	         'nmme_ncep-cfsv2',	        'nmme_cmc1-cancm3',	           'parx_parx-sst',	           'parx_parx-sst',	'nmme_nasa-gmao-062012', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3']
'sao_francisco_paulo_afonso':							[        'nmme_cmc2-cancm4',         'nmme_cmc1-cancm3',		 'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01',	         'nmme_ncep-cfsv2',	                     'par',	           'parx_parx-sst',	           'parx_parx-sst',	'nmme_nasa-gmao-062012', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3']
'sao_francisco_queimado':								[        'nmme_cmc2-cancm4',    'nmme_cola-rsmas-ccsm4',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	         'nmme_ncep-cfsv2',	                     'par',	                 'echam46',	                     'par',	     'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3']
'sao_francisco_retiro_baixo':							[        'nmme_cmc2-cancm4',    'nmme_cola-rsmas-ccsm4',	     'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01',	         'nmme_ncep-cfsv2',	   'nmme_cola-rsmas-ccsm4',	           'parx_parx-sst',	           'parx_parx-sst',	'nmme_nasa-gmao-062012', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3']
'sao_francisco_sobradinho':								[        'nmme_cmc2-cancm4',         'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01', 	         'nmme_ncep-cfsv2',	                     'par',	                     'par',	                     'par',	     'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	     'nmme_cmc1-cancm3']
'sao_francisco_sobradinho_inc':							[        'nmme_cmc2-cancm4',         'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01',	         'nmme_ncep-cfsv2',	                     'par',	           'parx_parx-sst',	                     'par',	     'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3']
'sao_francisco_tres_marias':							[        'nmme_cmc2-cancm4',         'nmme_cmc1-cancm3',	              'echam46', 'nmme_gfdl-cm2p5-flor-b01',	                 'echam46',	                 'echam46',	                     'par',	                     'par'	'nmme_nasa-gmao-062012', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3']
'sao_francisco_xingo':									[        'nmme_cmc2-cancm4',         'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3', 'nmme_gfdl-cm2p5-flor-b01',	         'nmme_ncep-cfsv2',	                     'par',	           'parx_parx-sst',	           'parx_parx-sst',	'nmme_nasa-gmao-062012', 'nmme_gfdl-cm2p5-flor-b01',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc1-cancm3']
'tiete_bariri':											[                     'par',    'nmme_nasa-gmao-062012',	        'parx_parx-sst',	                  'par',	   'nmme_cola-rsmas-ccsm4',   	    'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	   'nmme_nasa-gmao-062012', 	 'nmme_cmc1-cancm3',  	        'parx_parx-sst',	              'echam46',	        'parx_parx-sst']
'tiete_bariri_art':										[                     'par',    'nmme_nasa-gmao-062012',	        'parx_parx-sst',	                  'par',	   'nmme_cola-rsmas-ccsm4',  	    'nmme_cmc1-cancm3',    'nmme_cola-rsmas-ccsm4',	                 'echam46',	     'nmme_cmc1-cancm3',	                  'par',	              'echam46',	        'parx_parx-sst']
'tiete_barra_bonita':								  	[                     'par',                  'echam46',	        'parx_parx-sst',	                  'par',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	   'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	        'parx_parx-sst',	              'echam46',	              'echam46']
'tiete_barra_bonita_art':								[                     'par',    'nmme_nasa-gmao-062012',	        'parx_parx-sst',	'nmme_nasa-gmao-062012',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	                 'echam46',	   'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	                  'par',	              'echam46',	              'echam46']
'tiete_billings':										['nmme_gfdl-cm2p5-flor-b01',    'nmme_nasa-gmao-062012',	                  'par',	                  'par',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	   'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4',	        'parx_parx-sst']
'tiete_billings_art':									[                     'par',    'nmme_nasa-gmao-062012',	                  'par',	                  'par',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	                 'echam46',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4',	        'parx_parx-sst']
'tiete_billings_mais_pedras':							['nmme_gfdl-cm2p5-flor-b01',    'nmme_nasa-gmao-062012',	                  'par',	                  'par',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	   'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01',	        'parx_parx-sst']
'tiete_edgard_de_souza':								['nmme_gfdl-cm2p5-flor-b01',    'nmme_nasa-gmao-062012',	        'parx_parx-sst',	     'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	   'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	              'echam46',	              'echam46',	        'parx_parx-sst']
'tiete_edgard_de_souza_sem_tributarios':				['nmme_gfdl-cm2p5-flor-b01',    'nmme_nasa-gmao-062012',	        'parx_parx-sst',	     'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	   'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	              'echam46',	              'echam46',	        'parx_parx-sst']
'tiete_guarapiranga':								    [     	          'echam46',                  'echam46',	              'echam46',	              'echam46',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	                 'echam46',	     'nmme_cmc1-cancm3',	        'parx_parx-sst', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46']
'tiete_ibitinga':										[                 'echam46',    'nmme_nasa-gmao-062012',	        'parx_parx-sst',	              'echam46',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	                 'echam46',	     'nmme_cmc1-cancm3',	              'echam46',	              'echam46',	        'parx_parx-sst']
'tiete_ibitinga_art':									[                     'par',    'nmme_nasa-gmao-062012',	        'parx_parx-sst',	              'echam46',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	                 'echam46',	     'nmme_cmc1-cancm3',	              'echam46',	              'echam46',	        'parx_parx-sst']
'tiete_nova_avanhandava':								[                     'par',                  'echam46',	              'echam46',	                  'par',	   'nmme_cola-rsmas-ccsm4',     	'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	   'nmme_nasa-gmao-062012',  	 'nmme_cmc1-cancm3',	                  'par',	              'echam46',	                  'par']
'tiete_nova_avanhandava_art':							[                     'par',                  'echam46',	              'echam46',	              'echam46',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	                 'echam46', 	             'echam46',	     'nmme_cmc1-cancm3',	                  'par',	              'echam46',  	        'parx_parx-sst']
'tiete_pedreira':										[                     'par',    'nmme_nasa-gmao-062012',	                  'par',	                  'par',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	                 'echam46',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm3',	     'nmme_cmc2-cancm4',	        'parx_parx-sst']
'tiete_ponte_nova':										['nmme_gfdl-cm2p5-flor-b01',    'nmme_nasa-gmao-062012',	                  'par',	                  'par',	   'nmme_cola-rsmas-ccsm4',    	    'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	   'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm3',	                  'par',	'nmme_cola-rsmas-ccsm4']
'tiete_promissao':										[                 'echam46',                  'echam46',	              'echam46',	                  'par',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	   'nmme_nasa-gmao-062012',	     'nmme_cmc1-cancm3',	              'echam46',	     'nmme_cmc2-cancm4',	                  'par']
'tiete_promissao_art':									[                     'par',                   'cham46',	              'echam46',	              'echam46',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	                 'echam46',	     'nmme_cmc1-cancm3',	              'echam46',	              'echam46',	        'parx_parx-sst']
'tiete_traicao':										['nmme_gfdl-cm2p5-flor-b01',    'nmme_nasa-gmao-062012',	                  'par',	                  'par',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	                 'echam46',	                 'echam46',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm3', 'nmme_gfdl-cm2p5-flor-b01',	        'parx_parx-sst']
'tiete_tres_irmaos':									[                     'par',                  'echam46',	              'echam46',	     'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3',	                  'par',	              'echam46',	        'parx_parx-sst']
'tiete_tres_irmaos_art':								[                     'par',                  'echam46',	              'echam46',	              'echam46',	   'nmme_cola-rsmas-ccsm4',	        'nmme_cmc1-cancm3',	                 'echam46',	                 'echam46',	     'nmme_cmc1-cancm3',	                  'par',	              'echam46',	        'parx_parx-sst']
'tocantins_cana_brava':									[        'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3',	        'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	                 'echam46',	   'nmme_nasa-gmao-062012', 	          'echam46',	              'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'tocantins_estreito_tocantins':							[        'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc2-cancm4',	              'echam46',	                 'echam46',	         'nmme_ncep-cfsv2',	                     'par',    'nmme_nasa-gmao-062012',	'nmme_nasa-gmao-062012',	              'echam46',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm3']
'tocantins_lajeado':									[        'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3',	                 'echam46',	         'nmme_ncep-cfsv2',	                 'echam46',	   'nmme_nasa-gmao-062012',	'nmme_nasa-gmao-062012',	              'echam46',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm3']
'tocantins_peixe_angical':								[        'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01',	              'echam46',	              'echam46',	        'nmme_cmc1-cancm3',	                 'echam46',	                 'echam46',	   'nmme_nasa-gmao-062012',	'nmme_nasa-gmao-062012',	              'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'tocantins_sao_salvador':								[        'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3', 	        'nmme_cmc1-cancm3',	         'nmme_ncep-cfsv2',	                 'echam46',	   'nmme_nasa-gmao-062012',	'nmme_nasa-gmao-062012',	              'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm3']
'tocantins_serra_da_mesa':								[        'nmme_cmc2-cancm4', 'nmme_gfdl-cm2p5-flor-b01',	     'nmme_cmc1-cancm3',	              'echam46',	        'nmme_cmc1-cancm3',	                 'echam46',	                 'echam46',	   'nmme_nasa-gmao-062012',	'nmme_nasa-gmao-062012',	              'echam46',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm3']
'tocantins_tucurui':									[        'nmme_cmc2-cancm4',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	     'nmme_cmc1-cancm3',	        'nmme_cmc1-cancm3',	                     'par',	                     'par',	   'nmme_nasa-gmao-062012',	'nmme_nasa-gmao-062012',	'nmme_cola-rsmas-ccsm3',	      'nmme_ncep-cfsv2',	'nmme_cola-rsmas-ccsm3']
'uruguai_barra_grande':									[         'nmme_ncep-cfsv2',         'nmme_cmc2-cancm4',	        'parx_parx-sst',	'nmme_cola-rsmas-ccsm4',	         'nmme_ncep-cfsv2',            	         'par',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	        'parx_parx-sst',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3']
'uruguai_campos_novos':									[                 'echam46',                  'echam46',	              'echam46',    'nmme_cola-rsmas-ccsm4',	         'nmme_ncep-cfsv2',	         'nmme_ncep-cfsv2',	   'nmme_cola-rsmas-ccsm3',	   'nmme_cola-rsmas-ccsm3',	                  'par',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3']
'uruguai_foz_do_chapeco':								[         'nmme_ncep-cfsv2',         'nmme_cmc2-cancm4',	              'echam46',	'nmme_cola-rsmas-ccsm4',	         'nmme_ncep-cfsv2',	         'nmme_ncep-cfsv2',	   'nmme_cola-rsmas-ccsm3',	   'nmme_cola-rsmas-ccsm3',	                  'par',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3']
'uruguai_garibaldi':									[                 'echam46',         'nmme_cmc2-cancm4',	              'echam46',	'nmme_cola-rsmas-ccsm4',	         'nmme_ncep-cfsv2',	         'nmme_ncep-cfsv2',	   'nmme_cola-rsmas-ccsm3',	   'nmme_cola-rsmas-ccsm3',	                  'par',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3']
'uruguai_ita':											[   'nmme_cola-rsmas-ccsm3',         'nmme_cmc2-cancm4',	              'echam46',	'nmme_cola-rsmas-ccsm4',	         'nmme_ncep-cfsv2',  	     'nmme_ncep-cfsv2',	   'nmme_cola-rsmas-ccsm3',	   'nmme_cola-rsmas-ccsm3',	                  'par',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3']
'uruguai_machadinho':									[   'nmme_cola-rsmas-ccsm3',                  'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm4',	                 'echam46',	         'nmme_ncep-cfsv2',	   'nmme_cola-rsmas-ccsm3',	         'nmme_ncep-cfsv2',	                  'par',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3']
'uruguai_monjolinho':									[   'nmme_cola-rsmas-ccsm3',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	                 'echam46',	                     'par',	   'nmme_cola-rsmas-ccsm3',	   'nmme_cola-rsmas-ccsm3',	        'parx_parx-sst',	'nmme_cola-rsmas-ccsm4',	              'echam46',	     'nmme_cmc1-cancm3']
'uruguai_passo_fundo':									[   'nmme_cola-rsmas-ccsm3',         'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3',	'nmme_cola-rsmas-ccsm4',	                 'echam46',	                     'par',	   'nmme_cola-rsmas-ccsm3',	                 'echam46',	        'parx_parx-sst',	'nmme_cola-rsmas-ccsm4',	              'echam46',	     'nmme_cmc1-cancm3']
'uruguai_passo_sao_joao':								[   'nmme_cola-rsmas-ccsm3',                  'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm4',	                 'echam46',	                     'par',    	             'echam46',	                 'echam46',			'parx_parx-sst',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc2-cancm4',	              'echam46']
'uruguai_quebra_queixo':								[   'nmme_cola-rsmas-ccsm3',         'nmme_cmc2-cancm4',	              'echam46',	'nmme_cola-rsmas-ccsm4',	         'nmme_ncep-cfsv2',	           'parx_parx-sst',	   'nmme_cola-rsmas-ccsm3',	   'nmme_cola-rsmas-ccsm3',			'parx_parx-sst',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3']
'uruguai_sao_jose':										[   'nmme_cola-rsmas-ccsm3',                  'echam46',	              'echam46',	'nmme_cola-rsmas-ccsm4',	                 'echam46', 	                 'par',	                 'echam46',	                 'echam46',			'parx_parx-sst',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc2-cancm4',	              'echam46']
'uruguai_sao_roque':									[                 'echam46',         'nmme_cmc2-cancm4',	              'echam46',	'nmme_cola-rsmas-ccsm4',	         'nmme_ncep-cfsv2',	         'nmme_ncep-cfsv2',	   'nmme_cola-rsmas-ccsm3',	   'nmme_cola-rsmas-ccsm3',					  'par',	'nmme_cola-rsmas-ccsm4',	     'nmme_cmc2-cancm4',	     'nmme_cmc1-cancm3']
}

